package com.pbm5.bugtracker.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA Entity representing the membership relationship between a User and a
 * Project.
 * 
 * This is a junction/association table that handles the many-to-many
 * relationship
 * between users and projects, with additional metadata for:
 * - Role within the project (ADMIN, MEMBER)
 * - Approval workflow status (PENDING, ACTIVE, REJECTED)
 * - Audit trail (who approved, when joined, etc.)
 * 
 * Database Mapping:
 * - Table: project_members
 * - Primary Key: UUID id
 * - Unique Constraint: (project_id, user_id) - prevents duplicate memberships
 * - Foreign Keys: project_id -> projects(id), user_id -> users(id)
 * 
 * Business Rules:
 * - Each user can have at most one membership per project
 * - Only ACTIVE members can access project resources
 * - Membership requests start as PENDING and require admin approval
 * - Approval workflow tracks who approved and when
 * - At least one ADMIN must exist per project
 */
@Entity
@Table(name = "project_members", uniqueConstraints = @UniqueConstraint(columnNames = { "project_id",
        "user_id" }, name = "uk_project_user"))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id") // Only use ID to avoid circular references
@ToString(exclude = { "project" }) // Avoid circular references in toString
@Slf4j
public class ProjectMember {

    /**
     * Primary key using UUID for consistency with other entities
     * Auto-generated by JPA
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", updatable = false, nullable = false)
    @JsonProperty("id")
    private UUID id;

    /**
     * Many-to-One relationship with Project
     * Multiple members can belong to one project
     * 
     * Fetch Strategy: LAZY to avoid unnecessary queries
     * Join Column: Maps to project_id foreign key
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id", nullable = false, foreignKey = @ForeignKey(name = "fk_project_member_project"))
    @NotNull(message = "Project is required for membership")
    @JsonIgnore // Avoid circular reference in JSON serialization
    private Project project;

    /**
     * Reference to the User who is a member of the project
     * We store UUID instead of full User entity to avoid complex relationships
     * and improve performance
     */
    @Column(name = "user_id", nullable = false)
    @NotNull(message = "User ID is required for membership")
    @JsonProperty("userId")
    private UUID userId;

    /**
     * Role of the user within this project
     * Determines what actions the user can perform
     * 
     * Default: MEMBER (most common role)
     * ADMIN: Full project management permissions
     * MEMBER: Basic project access permissions
     * Note: For PENDING requests, role is set but not effective until approved
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    @NotNull(message = "Role is required for membership")
    @JsonProperty("role")
    private ProjectRole role = ProjectRole.MEMBER;

    /**
     * Status of this membership for approval workflow
     * Tracks the lifecycle from request to active participation
     * 
     * PENDING: User requested to join, awaiting approval
     * ACTIVE: User is approved and can access project
     * REJECTED: User request was rejected by admin
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @NotNull(message = "Status is required for membership")
    @JsonProperty("status")
    private MemberStatus status = MemberStatus.PENDING;

    /**
     * Timestamp when user actually joined the project (after approval)
     * Only set for ACTIVE members
     * NULL for PENDING/REJECTED members
     */
    @Column(name = "joined_at")
    @JsonProperty("joinedAt")
    private LocalDateTime joinedAt;

    /**
     * Timestamp when user first requested to join
     * Always populated when membership record is created
     * Preserved even after approval/rejection for audit purposes
     */
    @Column(name = "requested_at", nullable = false)
    @NotNull(message = "Request timestamp is required")
    @JsonProperty("requestedAt")
    private LocalDateTime requestedAt = LocalDateTime.now();

    /**
     * Reference to admin user who approved/rejected the membership
     * NULL for PENDING status
     * Set when admin takes action (approve/reject)
     */
    @Column(name = "approved_by")
    @JsonProperty("approvedBy")
    private UUID approvedBy;

    /**
     * Timestamp when membership was approved/rejected
     * NULL for PENDING status
     * Set when admin takes action
     */
    @Column(name = "approved_at")
    @JsonProperty("approvedAt")
    private LocalDateTime approvedAt;

    /**
     * Audit timestamp for record creation
     * Automatically set by Hibernate when entity is first persisted
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    @JsonProperty("createdAt")
    private LocalDateTime createdAt;

    /**
     * Audit timestamp for record updates
     * Automatically updated by Hibernate when entity is modified
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    @JsonProperty("updatedAt")
    private LocalDateTime updatedAt;

    // ===============================
    // CONSTRUCTORS FOR COMMON USE CASES
    // ===============================

    /**
     * Constructor for creating a new membership request
     * Sets up PENDING status with PENDING role (no access until approved)
     * 
     * @param project The project user wants to join
     * @param userId  The user requesting membership
     */
    public ProjectMember(Project project, UUID userId) {
        this.project = project;
        this.userId = userId;
        this.role = ProjectRole.PENDING; // PENDING role (no access until approved)
        this.status = MemberStatus.PENDING;
        this.requestedAt = LocalDateTime.now();

        log.debug("Created new membership request for user {} in project {}",
                userId, project != null ? project.getId() : "null");
    }

    /**
     * Constructor for creating membership with specific role
     * Used when admin directly adds users or for project creators
     * 
     * @param project The project
     * @param userId  The user
     * @param role    The role to assign
     * @param status  The initial status
     */
    public ProjectMember(Project project, UUID userId, ProjectRole role, MemberStatus status) {
        this.project = project;
        this.userId = userId;
        this.role = role;
        this.status = status;
        this.requestedAt = LocalDateTime.now();

        // If creating as ACTIVE, set joined timestamp
        if (MemberStatus.ACTIVE.equals(status)) {
            this.joinedAt = LocalDateTime.now();
        }

        log.debug("Created membership for user {} in project {} with role {} and status {}",
                userId, project != null ? project.getId() : "null", role, status);
    }

    // ===============================
    // BUSINESS LOGIC METHODS
    // ===============================

    /**
     * Approve this membership request
     * Transitions from PENDING to ACTIVE status
     * Changes role from PENDING to MEMBER
     * Sets approval metadata and joined timestamp
     * 
     * @param approverUserId UUID of admin who approved the request
     * @throws IllegalStateException if membership is not in PENDING status
     */
    public void approve(UUID approverUserId) {
        log.debug("Approving membership request for user {} in project {}",
                userId, project != null ? project.getId() : "null");

        if (!MemberStatus.PENDING.equals(this.status)) {
            throw new IllegalStateException(
                    "Cannot approve membership with status: " + this.status +
                            ". Only PENDING requests can be approved.");
        }

        if (approverUserId == null) {
            throw new IllegalArgumentException("Approver user ID is required");
        }

        LocalDateTime now = LocalDateTime.now();

        this.status = MemberStatus.ACTIVE;
        this.role = ProjectRole.MEMBER; // Change from PENDING to MEMBER role
        this.approvedBy = approverUserId;
        this.approvedAt = now;
        this.joinedAt = now;

        log.info("Approved membership for user {} in project {} by admin {} - role changed from PENDING to MEMBER",
                userId, project != null ? project.getId() : "null", approverUserId);
    }

    /**
     * Reject this membership request
     * Transitions from PENDING to REJECTED status
     * Resets role back to PENDING (no access until re-approved)
     * Sets approval metadata but no joined timestamp
     * 
     * @param rejecterUserId UUID of admin who rejected the request
     * @throws IllegalStateException if membership is not in PENDING status
     */
    public void reject(UUID rejecterUserId) {
        log.debug("Rejecting membership request for user {} in project {}",
                userId, project != null ? project.getId() : "null");

        if (!MemberStatus.PENDING.equals(this.status)) {
            throw new IllegalStateException(
                    "Cannot reject membership with status: " + this.status +
                            ". Only PENDING requests can be rejected.");
        }

        if (rejecterUserId == null) {
            throw new IllegalArgumentException("Rejecter user ID is required");
        }

        this.status = MemberStatus.REJECTED;
        this.role = ProjectRole.PENDING; // Reset role back to PENDING (no access)
        this.approvedBy = rejecterUserId;
        this.approvedAt = LocalDateTime.now();
        // joinedAt remains null for rejected requests

        log.info("Rejected membership for user {} in project {} by admin {} - role reset to PENDING",
                userId, project != null ? project.getId() : "null", rejecterUserId);
    }

    /**
     * Update the role of this member
     * Can only be done for ACTIVE members
     * 
     * @param newRole The new role to assign
     * @throws IllegalStateException if member is not ACTIVE
     */
    public void updateRole(ProjectRole newRole) {
        log.debug("Updating role for user {} in project {} from {} to {}",
                userId, project != null ? project.getId() : "null", role, newRole);

        if (!MemberStatus.ACTIVE.equals(this.status)) {
            throw new IllegalStateException(
                    "Cannot update role for membership with status: " + this.status +
                            ". Only ACTIVE members can have their roles updated.");
        }

        if (newRole == null) {
            throw new IllegalArgumentException("New role cannot be null");
        }

        ProjectRole oldRole = this.role;
        this.role = newRole;

        log.info("Updated role for user {} in project {} from {} to {}",
                userId, project != null ? project.getId() : "null", oldRole, newRole);
    }

    /**
     * Check if this member is active and can access project resources
     * 
     * @return true if member has ACTIVE status
     */
    public boolean isActive() {
        return MemberStatus.ACTIVE.equals(this.status);
    }

    /**
     * Check if this member is pending approval
     * 
     * @return true if member has PENDING status
     */
    public boolean isPending() {
        return MemberStatus.PENDING.equals(this.status);
    }

    /**
     * Check if this member request was rejected
     * 
     * @return true if member has REJECTED status
     */
    public boolean isRejected() {
        return MemberStatus.REJECTED.equals(this.status);
    }

    /**
     * Check if this member has admin privileges in the project
     * 
     * @return true if member has ADMIN role
     */
    public boolean isAdmin() {
        return ProjectRole.ADMIN.equals(this.role);
    }

    /**
     * Check if this member can manage other members
     * Currently only admins can manage members
     * 
     * @return true if member can manage other project members
     */
    public boolean canManageMembers() {
        return isActive() && role.canManageMembers();
    }

    /**
     * Check if this member can modify project settings
     * Currently only admins can modify project settings
     * 
     * @return true if member can modify project
     */
    public boolean canModifyProject() {
        return isActive() && role.canModifyProject();
    }

    /**
     * Get project ID for convenience
     * Avoids need to load full project entity
     * 
     * @return UUID of the associated project
     */
    public UUID getProjectId() {
        return project != null ? project.getId() : null;
    }

    /**
     * JPA lifecycle callback to validate data consistency before persisting
     */
    @PrePersist
    @PreUpdate
    protected void validateConsistency() {
        log.debug("Validating consistency for project member: {}", id);

        // Ensure approval data is consistent with status
        if (MemberStatus.ACTIVE.equals(status)) {
            if (approvedBy == null || approvedAt == null || joinedAt == null) {
                throw new IllegalStateException(
                        "ACTIVE members must have approval metadata set");
            }
        }

        if (MemberStatus.REJECTED.equals(status)) {
            if (approvedBy == null || approvedAt == null) {
                throw new IllegalStateException(
                        "REJECTED members must have approval metadata set");
            }
            if (joinedAt != null) {
                throw new IllegalStateException(
                        "REJECTED members should not have joined timestamp");
            }
        }

        if (MemberStatus.PENDING.equals(status)) {
            if (approvedBy != null || approvedAt != null || joinedAt != null) {
                throw new IllegalStateException(
                        "PENDING members should not have approval metadata");
            }
        }

        log.debug("Consistency validation passed for project member: {}", id);
    }

    /**
     * Create a new membership request for a user to join a project
     * Factory method for common use case
     * 
     * @param project The project to join
     * @param userId  The user requesting membership
     * @return New ProjectMember in PENDING status
     */
    public static ProjectMember createRequest(Project project, UUID userId) {
        return new ProjectMember(project, userId);
    }

    /**
     * Create an active membership (bypassing approval workflow)
     * Used for project creators or admin-added members
     * 
     * @param project The project
     * @param userId  The user
     * @param role    The role to assign
     * @return New ProjectMember in ACTIVE status
     */
    public static ProjectMember createActive(Project project, UUID userId, ProjectRole role) {
        return new ProjectMember(project, userId, role, MemberStatus.ACTIVE);
    }
}